CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ClassCourses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Section" text,
    "AcademicYear" text,
    CONSTRAINT "PK_ClassCourses" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(200) NOT NULL,
    "Email" character varying(256) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Subjects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Code" text,
    "ClassCourseId" integer NOT NULL,
    CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subjects_ClassCourses_ClassCourseId" FOREIGN KEY ("ClassCourseId") REFERENCES "ClassCourses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StudentEnrollments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" integer NOT NULL,
    "ClassCourseId" integer NOT NULL,
    CONSTRAINT "PK_StudentEnrollments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentEnrollments_ClassCourses_ClassCourseId" FOREIGN KEY ("ClassCourseId") REFERENCES "ClassCourses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StudentEnrollments_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TeacherSubjectAssignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TeacherId" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    "ClassCourseId" integer NOT NULL,
    CONSTRAINT "PK_TeacherSubjectAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TeacherSubjectAssignments_ClassCourses_ClassCourseId" FOREIGN KEY ("ClassCourseId") REFERENCES "ClassCourses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TeacherSubjectAssignments_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TeacherSubjectAssignments_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Assignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(300) NOT NULL,
    "Description" text,
    "TeacherSubjectAssignmentId" integer NOT NULL,
    "Deadline" timestamp with time zone NOT NULL,
    "MaxMarks" integer NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Assignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Assignments_TeacherSubjectAssignments_TeacherSubjectAssignm~" FOREIGN KEY ("TeacherSubjectAssignmentId") REFERENCES "TeacherSubjectAssignments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Submissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AssignmentId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "Content" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "Status" integer NOT NULL,
    "Marks" numeric(6,2),
    "Feedback" text,
    "GradedAt" timestamp with time zone,
    "GradedByUserId" integer,
    CONSTRAINT "PK_Submissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Submissions_Assignments_AssignmentId" FOREIGN KEY ("AssignmentId") REFERENCES "Assignments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Submissions_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Assignments_TeacherSubjectAssignmentId" ON "Assignments" ("TeacherSubjectAssignmentId");

CREATE INDEX "IX_StudentEnrollments_ClassCourseId" ON "StudentEnrollments" ("ClassCourseId");

CREATE UNIQUE INDEX "IX_StudentEnrollments_StudentId_ClassCourseId" ON "StudentEnrollments" ("StudentId", "ClassCourseId");

CREATE INDEX "IX_Subjects_ClassCourseId" ON "Subjects" ("ClassCourseId");

CREATE UNIQUE INDEX "IX_Submissions_AssignmentId_StudentId" ON "Submissions" ("AssignmentId", "StudentId");

CREATE INDEX "IX_Submissions_StudentId" ON "Submissions" ("StudentId");

CREATE INDEX "IX_TeacherSubjectAssignments_ClassCourseId" ON "TeacherSubjectAssignments" ("ClassCourseId");

CREATE INDEX "IX_TeacherSubjectAssignments_SubjectId" ON "TeacherSubjectAssignments" ("SubjectId");

CREATE UNIQUE INDEX "IX_TeacherSubjectAssignments_TeacherId_SubjectId_ClassCourseId" ON "TeacherSubjectAssignments" ("TeacherId", "SubjectId", "ClassCourseId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260807190803_InitialCreate', '9.0.7');

COMMIT;

